# Generated by Django 3.2 on 2021-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='crated at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
            ],
            options={
                'verbose_name': 'todo',
                'verbose_name_plural': 'todos',
                'ordering': ['title'],
            },
        ),
    ]
