name: Build An Image for Backend Application

on:
  workflow_dispatch:

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: backend-image
          dockerfile: ./backend/Dockerfile

